FROM node:22-alpine AS media
WORKDIR /app
RUN apk add --no-cache ffmpeg python3 py3-pip && \
    pip3 install --break-system-packages yt-dlp
RUN corepack enable
COPY package.json package-lock.json ./
RUN npm ci --ignore-scripts
COPY . .
RUN npx prisma generate
RUN npm run build
CMD ["node", "dist/index.js"]
