// ── Shared Prompt Templates ──────────────────────────────────────

import { loadBrandStrategy } from "../my_approach/loader";
import { loadBrandPrompt } from "./brand-loader";

/**
 * Build a complete system prompt by combining org brand voice with agent-specific instructions.
 * If brandVoice is not passed explicitly, attempts to load from my_approach/{orgId}/.
 * Also loads the org's brand-prompt.md from clients/{orgId}/ (generated by Brand Persona Agent).
 */
export function buildSystemPrompt(
  agentInstructions: string,
  brandVoice?: string,
  orgId?: string,
): string {
  const parts: string[] = [];

  // Load brand-prompt.md from client plugin directory (generated by Brand Persona Agent)
  if (orgId) {
    const brandPrompt = loadBrandPrompt(orgId);
    if (brandPrompt) {
      parts.push(`## Brand Persona\n${brandPrompt}`);
    }
  }

  // Try loading from my_approach if no explicit brand voice and orgId is available
  let resolvedBrandVoice = brandVoice;
  let toneExamples: string | null = null;

  if (!resolvedBrandVoice && orgId) {
    const strategy = loadBrandStrategy(orgId);
    resolvedBrandVoice = strategy.brandVoice ?? undefined;
    toneExamples = strategy.toneExamples;
  }

  if (resolvedBrandVoice) {
    parts.push(`## Brand Voice\n${resolvedBrandVoice}`);
  }

  if (toneExamples) {
    parts.push(`## Tone Examples\n${toneExamples}`);
  }

  parts.push(`## Instructions\n${agentInstructions}`);

  return parts.join("\n\n");
}
