#!/bin/bash
set -eo pipefail

# ── Parallel Speedrun via Git Worktrees (Sliding Window of 3) ────────────────
# Each issue gets an isolated worktree so multiple Claude instances build
# simultaneously. Ship phase runs sequentially from main checkout.
# Compatible with bash 3.2+ (no associative arrays).

PROJECT_DIR="$(cd "$(dirname "$0")/.." && pwd)"

# Per-user branch prefix (override via SHIPIT_USER env var)
_raw_user="${SHIPIT_USER:-$(git config user.name 2>/dev/null || echo user)}"
BRANCH_PREFIX="$(echo "$_raw_user" | tr '[:upper:]' '[:lower:]' | tr -cs 'a-z0-9' '-' | sed 's/^-//;s/-$//')"
unset _raw_user
GH_USER=$(gh api user -q '.login' 2>/dev/null || true)

WORKTREE_BASE="$PROJECT_DIR/.claude/worktrees"
MAX_PARALLEL=3
LAUNCH_DELAY=5

# ── Signal handler: kill children + clean up on Ctrl+C ────────────────────────
cleanup_on_signal() {
  echo -e "\n${RED}Caught signal — killing child builds...${NC}"
  kill 0 2>/dev/null || true
  wait 2>/dev/null || true
  cd "$PROJECT_DIR" 2>/dev/null || true
  for wt in "$WORKTREE_BASE"/feature-*; do
    [[ -d "$wt" ]] && git worktree remove "$wt" --force 2>/dev/null || true
  done
  git worktree prune 2>/dev/null || true
  echo -e "${RED}Cleaned up. Exiting.${NC}"
  exit 130
}
trap cleanup_on_signal INT TERM

# Colors
RED='\033[0;31m'
GREEN='\033[0;32m'
YELLOW='\033[1;33m'
BLUE='\033[0;34m'
CYAN='\033[0;36m'
NC='\033[0m'

# ── Parse issues (same 4 modes as speedrun) ──────────────────────────────────
ISSUES=()
LABEL="auto"

if [[ -z "$1" ]]; then
  while IFS= read -r num; do
    [[ -n "$num" ]] && ISSUES+=("$num")
  done < <(gh issue list -l "$LABEL" --state open --json number -q '.[].number' | sort -n)
elif [[ "$1" == *,* ]]; then
  IFS=',' read -ra ISSUES <<< "$1"
elif [[ "$1" == *-* ]]; then
  range_start="${1%-*}"
  range_end="${1#*-}"
  while IFS= read -r num; do
    [[ "$num" -ge "$range_start" && "$num" -le "$range_end" ]] && ISSUES+=("$num")
  done < <(gh issue list -l "$LABEL" --state open --json number -q '.[].number' | sort -n)
else
  ISSUES=("$1")
fi

if [[ ${#ISSUES[@]} -eq 0 ]]; then
  echo -e "${RED}No issues found${NC}"
  exit 1
fi

echo -e "${BLUE}══════════════════════════════════════════════════════${NC}"
echo -e "${BLUE}  Parallel Speedrun (window=$MAX_PARALLEL)${NC}"
echo -e "${BLUE}══════════════════════════════════════════════════════${NC}"
echo -e "${GREEN}Issues:${NC} ${ISSUES[*]}"
echo ""

# ── Guard: main checkout must be clean ────────────────────────────────────────
cd "$PROJECT_DIR"
if ! git diff --quiet 2>/dev/null || ! git diff --cached --quiet 2>/dev/null || [[ -n "$(git ls-files --others --exclude-standard 2>/dev/null)" ]]; then
  echo -e "${YELLOW}⚠ Auto-stashing uncommitted changes in main checkout${NC}"
  git stash push --include-untracked -m "auto-stash before parallel speedrun" 2>/dev/null || true
fi

# Ensure we're on the default branch
DEFAULT_BRANCH=$(git remote show origin 2>/dev/null | awk '/HEAD branch/{print $NF}')
DEFAULT_BRANCH="${DEFAULT_BRANCH:-main}"
CURRENT_BRANCH=$(git branch --show-current)
if [[ "$CURRENT_BRANCH" != "$DEFAULT_BRANCH" ]]; then
  echo -e "${YELLOW}Switching to $DEFAULT_BRANCH...${NC}"
  git checkout "$DEFAULT_BRANCH"
fi
git pull --ff-only origin "$DEFAULT_BRANCH" 2>/dev/null || true

# ── Worktree path helper (deterministic, no assoc array needed) ──────────────
wt_path_for() { echo "$WORKTREE_BASE/feature-$1"; }

# ── Create worktrees ─────────────────────────────────────────────────────────
mkdir -p "$WORKTREE_BASE"
VALID_ISSUES=()

for issue in "${ISSUES[@]}"; do
  wt_path=$(wt_path_for "$issue")
  branch="$BRANCH_PREFIX/feature-$issue"

  if [[ -d "$wt_path" ]]; then
    echo -e "${YELLOW}Worktree exists: $wt_path — reusing (syncing scripts)${NC}"
    # Sync latest scripts into reused worktrees (stale copies lack critical fixes)
    if [[ -d "$PROJECT_DIR/scripts" ]]; then
      mkdir -p "$wt_path/scripts"
      cp "$PROJECT_DIR/scripts/run-feature.sh" "$wt_path/scripts/run-feature.sh" 2>/dev/null || true
      # run-plan.sh is regenerated by run-feature.sh from template — no need to copy
    fi
  else
    echo -e "${CYAN}Creating worktree: feature-$issue${NC}"
    # Track remote branch if it exists but local doesn't
    if ! git rev-parse --verify "$branch" &>/dev/null && git rev-parse --verify "origin/$branch" &>/dev/null; then
      git branch --track "$branch" "origin/$branch" 2>/dev/null || true
    fi
    git worktree add "$wt_path" -b "$branch" "$DEFAULT_BRANCH" 2>/dev/null \
      || git worktree add "$wt_path" "$branch" 2>/dev/null \
      || { echo -e "${RED}Cannot create worktree for #$issue${NC}"; continue; }
  fi

  # Symlink Python venv if project has one (real dirs only, not existing symlinks)
  for venv_path in "$PROJECT_DIR"/.venv "$PROJECT_DIR"/*/.venv; do
    # Skip if not a real directory (glob miss, broken symlink, or already a symlink)
    [[ -d "$venv_path" && ! -L "$venv_path" ]] || continue
    _rel="${venv_path#$PROJECT_DIR/}"
    _target="$wt_path/$_rel"
    # Guard: skip if target already exists or would self-reference
    [[ -e "$_target" || -L "$_target" ]] && continue
    [[ "$_target" -ef "$venv_path" ]] 2>/dev/null && continue
    mkdir -p "$(dirname "$_target")"
    ln -sf "$venv_path" "$_target" 2>/dev/null || true
  done

  VALID_ISSUES+=("$issue")
done

echo -e "${GREEN}${#VALID_ISSUES[@]} worktrees ready${NC}"
echo ""

# ── PID tracking (parallel indexed arrays — bash 3.2 compatible) ─────────────
PID_ISSUES=()   # issue number at index i
PID_VALUES=()   # PID at index i
SUCCEEDED=()
FAILED=()
SKIPPED=()

active_count() { echo "${#PID_ISSUES[@]}"; }

# Launch a single issue in its worktree (background subshell)
launch_issue() {
  local issue=$1
  local wt_path
  wt_path=$(wt_path_for "$issue")
  local log_dir="$PROJECT_DIR/.claude/logs/feature-$issue"
  mkdir -p "$log_dir"

  echo -e "${BLUE}Launching issue #$issue in $wt_path${NC}"

  (
    # Prevent nested Claude instances from inheriting API config
    unset CLAUDECODE CLAUDE_CODE_ENTRYPOINT CLAUDE_CODE_SSE_PORT ANTHROPIC_BASE_URL ANTHROPIC_API_KEY API_TIMEOUT_MS 2>/dev/null || true

    # Claim issue — skip if assigned to someone else
    _assignees=$(gh issue view "$issue" --json assignees -q '.assignees[].login' 2>/dev/null || true)
    if [[ -n "$_assignees" && "$_assignees" != *"$GH_USER"* ]]; then
      echo "Skipping #$issue — assigned to $_assignees"
      touch "$log_dir/.skipped"
      exit 0
    fi
    [[ -z "$_assignees" && -n "$GH_USER" ]] && gh issue edit "$issue" --add-assignee "@me" 2>/dev/null || true

    export WORKTREE_PROJECT_DIR="$wt_path"

    # Prepend all project venvs to PATH
    for venv_path in "$wt_path"/.venv "$wt_path"/*/.venv; do
      [[ -d "$venv_path/bin" ]] && export PATH="$venv_path/bin:$PATH"
    done

    cd "$wt_path"
    "$wt_path/scripts/run-feature.sh" --issue "$issue" --skip-ship
  ) > "$log_dir/parallel.log" 2>&1 &

  PID_ISSUES+=("$issue")
  PID_VALUES+=("$!")
}

# Check all PIDs, remove finished ones, return 0 if any finished
check_done() {
  local new_issues=() new_pids=()
  local found_done=1  # 1 = false in bash
  local i

  for i in "${!PID_ISSUES[@]}"; do
    local issue="${PID_ISSUES[$i]}"
    local pid="${PID_VALUES[$i]}"

    if ! kill -0 "$pid" 2>/dev/null; then
      # Process finished
      wait "$pid" 2>/dev/null
      local rc=$?
      if [[ $rc -eq 0 && -f "$PROJECT_DIR/.claude/logs/feature-$issue/.skipped" ]]; then
        echo -e "${YELLOW}Issue #$issue skipped (assigned to another user)${NC}"
        SKIPPED+=("$issue")
      elif [[ $rc -eq 0 ]]; then
        echo -e "${GREEN}Issue #$issue completed successfully${NC}"
        SUCCEEDED+=("$issue")
      else
        echo -e "${RED}Issue #$issue failed (exit $rc)${NC}"
        FAILED+=("$issue")
      fi
      found_done=0
    else
      new_issues+=("$issue")
      new_pids+=("$pid")
    fi
  done

  PID_ISSUES=("${new_issues[@]}")
  PID_VALUES=("${new_pids[@]}")
  return $found_done
}

# ── Sliding window ───────────────────────────────────────────────────────────
QUEUE_IDX=0

# Initial launch (up to MAX_PARALLEL)
while [[ $QUEUE_IDX -lt ${#VALID_ISSUES[@]} && $(active_count) -lt $MAX_PARALLEL ]]; do
  launch_issue "${VALID_ISSUES[$QUEUE_IDX]}"
  QUEUE_IDX=$((QUEUE_IDX + 1))
  [[ $QUEUE_IDX -lt ${#VALID_ISSUES[@]} && $(active_count) -lt $MAX_PARALLEL ]] && sleep "$LAUNCH_DELAY"
done

# Poll until all done
while [[ $(active_count) -gt 0 ]]; do
  if check_done; then
    # Slot freed — launch next if available
    while [[ $QUEUE_IDX -lt ${#VALID_ISSUES[@]} && $(active_count) -lt $MAX_PARALLEL ]]; do
      sleep "$LAUNCH_DELAY"
      launch_issue "${VALID_ISSUES[$QUEUE_IDX]}"
      QUEUE_IDX=$((QUEUE_IDX + 1))
    done
  fi
  [[ $(active_count) -gt 0 ]] && sleep 10 || true
done

# ── Results ──────────────────────────────────────────────────────────────────
echo ""
echo -e "${BLUE}══════════════════════════════════════════════════════${NC}"
echo -e "${BLUE}  Build Results${NC}"
echo -e "${BLUE}══════════════════════════════════════════════════════${NC}"
echo -e "${GREEN}Succeeded:${NC} ${SUCCEEDED[*]:-none}"
echo -e "${YELLOW}Skipped:${NC} ${SKIPPED[*]:-none}"
echo -e "${RED}Failed:${NC} ${FAILED[*]:-none}"
echo ""

# ── Release worktrees (copy state, then remove so branches are free) ────────
echo ""
echo -e "${CYAN}Releasing worktrees (freeing branches for ship)...${NC}"
cd "$PROJECT_DIR"

for issue in "${SUCCEEDED[@]}" "${SKIPPED[@]}" "${FAILED[@]}"; do
  wt_path=$(wt_path_for "$issue")
  main_log_dir="$PROJECT_DIR/.claude/logs/feature-$issue"
  wt_log_dir="$wt_path/.claude/logs/feature-$issue"
  mkdir -p "$main_log_dir"

  # Copy all logs + state (including dotfiles like .plan_issue) from worktree
  if [[ -d "$wt_log_dir" ]]; then
    cp -r "$wt_log_dir"/. "$main_log_dir/" 2>/dev/null || true
  fi

  if [[ -d "$wt_path" ]]; then
    git worktree remove "$wt_path" --force 2>/dev/null || true
  fi
done
git worktree prune 2>/dev/null || true

# Clean up any broken .venv symlinks left in main project after worktree removal
for _venv in "$PROJECT_DIR"/.venv "$PROJECT_DIR"/*/.venv; do
  [[ -L "$_venv" && ! -d "$_venv" ]] && rm -f "$_venv" 2>/dev/null || true
done
echo -e "${GREEN}Worktrees released${NC}"

# ── Ship sequentially from main checkout ─────────────────────────────────────
SHIPPED=()
SHIP_FAILED=()

if [[ ${#SUCCEEDED[@]} -eq 0 ]]; then
  echo -e "${RED}No issues to ship${NC}"
else
  echo -e "${BLUE}══════════════════════════════════════════════════════${NC}"
  echo -e "${BLUE}  Sequential Ship Phase${NC}"
  echo -e "${BLUE}══════════════════════════════════════════════════════${NC}"

  cd "$PROJECT_DIR"

  for issue in "${SUCCEEDED[@]}"; do
    main_log_dir="$PROJECT_DIR/.claude/logs/feature-$issue"

    # Pre-iteration cleanup: ensure clean state before each ship (prevents cascade)
    cd "$PROJECT_DIR"
    git merge --abort 2>/dev/null || true
    git checkout "$DEFAULT_BRANCH" 2>/dev/null || true
    # Drop ALL shipping stashes (not just top)
    _stash_indices=()
    while IFS= read -r _line; do
      if echo "$_line" | grep -q "auto-stash before shipping"; then
        _idx=$(echo "$_line" | sed 's/stash@{\([0-9]*\)}.*/\1/')
        _stash_indices+=("$_idx")
      fi
    done < <(git stash list 2>/dev/null)
    # Drop in reverse order (highest index first) to preserve indices
    for (( _i=${#_stash_indices[@]}-1; _i>=0; _i-- )); do
      git stash drop "stash@{${_stash_indices[$_i]}}" 2>/dev/null || true
    done

    echo -e "${CYAN}Shipping issue #$issue...${NC}"

    plan_issue=""
    if [[ -f "$main_log_dir/.plan_issue" ]]; then
      plan_issue=$(cat "$main_log_dir/.plan_issue")
      echo -e "${GREEN}  Plan issue: #$plan_issue${NC}"
    fi

    # Auto-stash dirty state before switching branches
    if ! git diff --quiet 2>/dev/null || ! git diff --cached --quiet 2>/dev/null || [[ -n "$(git ls-files --others --exclude-standard 2>/dev/null)" ]]; then
      git stash push --include-untracked -m "auto-stash before shipping #$issue" 2>/dev/null || true
    fi

    # Checkout the feature branch in main checkout
    branch="$BRANCH_PREFIX/feature-$issue"
    git checkout "$branch" 2>/dev/null || {
      echo -e "${RED}  Cannot checkout $branch — skipping ship${NC}"
      SHIP_FAILED+=("$issue")
      continue
    }

    # Run ship phase
    ship_args=(--issue "$issue" --start-phase ship)
    [[ -n "$plan_issue" ]] && ship_args+=(--plan-issue "$plan_issue")

    if "$PROJECT_DIR/scripts/run-feature.sh" "${ship_args[@]}"; then
      echo -e "${GREEN}  Issue #$issue shipped${NC}"
      SHIPPED+=("$issue")
    else
      echo -e "${RED}  Issue #$issue ship failed${NC}"
      SHIP_FAILED+=("$issue")
      # Abort any lingering merge state before switching back
      git merge --abort 2>/dev/null || true
      git checkout "$DEFAULT_BRANCH" 2>/dev/null || true
    fi

    # Pop per-issue ship stash (pushed at top of loop)
    if git stash list 2>/dev/null | head -1 | grep -q "auto-stash before shipping #$issue"; then
      if ! git stash pop 2>/dev/null; then
        for _f in $(git diff --name-only --diff-filter=U 2>/dev/null); do
          case "$_f" in
            CLAUDE.md|scripts/run-plan.sh) git checkout --ours "$_f" 2>/dev/null ;;
            *) git checkout --theirs "$_f" 2>/dev/null ;;
          esac
          git add "$_f" 2>/dev/null
        done
        git stash drop 2>/dev/null || true
      fi
    fi
  done
fi

# Return to default branch and restore stashed changes
cd "$PROJECT_DIR"
git checkout "$DEFAULT_BRANCH" 2>/dev/null || true
if git stash list 2>/dev/null | head -1 | grep -q "auto-stash before parallel speedrun"; then
  if ! git stash pop 2>/dev/null; then
    # Auto-resolve: keep current for speedrun artifacts, stash for user files
    for _f in $(git diff --name-only --diff-filter=U 2>/dev/null); do
      case "$_f" in
        CLAUDE.md|scripts/run-plan.sh) git checkout --ours "$_f" 2>/dev/null ;;
        *) git checkout --theirs "$_f" 2>/dev/null ;;
      esac
      git add "$_f" 2>/dev/null
    done
    git stash drop 2>/dev/null || true
    echo -e "${GREEN}  ✓ Stash restored (auto-resolved speedrun artifact conflicts)${NC}"
  fi
fi

# ── Final summary ────────────────────────────────────────────────────────────
echo ""
echo -e "${GREEN}══════════════════════════════════════════════════════${NC}"
echo -e "${GREEN}  Parallel Speedrun Complete${NC}"
echo -e "${GREEN}══════════════════════════════════════════════════════${NC}"
echo -e "${GREEN}Shipped:${NC} ${SHIPPED[*]:-none}"
[[ ${#SKIPPED[@]} -gt 0 ]] && echo -e "${YELLOW}Skipped:${NC} ${SKIPPED[*]}"
ALL_FAILED=("${FAILED[@]}" "${SHIP_FAILED[@]}")
[[ ${#ALL_FAILED[@]} -gt 0 ]] && echo -e "${RED}Failed:${NC} ${ALL_FAILED[*]}"
exit 0
